// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    BaseUrl: "http://localhost:4000/"
  },
  environment: {
    BaseUrl: "http://localhost:4000/"
  }
});

export default function() {
  postman[Request]({
    name: "changeClendar show doctor calendar",
    id: "c0f706b0-ed5c-4fd7-83f2-b65e6244251b",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/changeClendar",
    data:
      '{\r\n    "id": "633ab0f123be88c950fb8a89",\r\n    "allawAllDoctors":false\r\n}'
  });

  postman[Request]({
    name: "changeClendar show all shecules",
    id: "ef51ede1-8a02-457c-9190-aed4859c9d5e",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/changeClendar",
    data:
      '{\r\n    "id": "633ab0f123be88c950fb8a89",\r\n    "allawAllDoctors":false\r\n}'
  });

  postman[Request]({
    name: "changePassword",
    id: "40b26270-653b-4553-b101-985a98a2147e",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/changePassword",
    data:
      '{\r\n    "id" : "633ab0f123be88c950fb8a89",\r\n    "email": "abcd@gmail.com",\r\n    "password":"Abcd@1234"\r\n}'
  });

  postman[Request]({
    name: "defineRequirements",
    id: "aadcdd19-17d2-4abb-be5e-e0a09e0d7e19",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/defineRequirements",
    data:
      '{\r\n    "id":"633ab0f123be88c950fb8a89",\r\n    "date":"2022-10-14",\r\n    "morning": true,\r\n    "evening": false,\r\n    "night":true\r\n\r\n}'
  });

  postman[Request]({
    name: "setSwappingShifts",
    id: "24588e42-75cc-4b01-8918-088c34040936",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/setSwappingShifts",
    data:
      '{\r\n  "id": "633ab0f123be88c950fb8a89",\r\n  "fromShiftofSchedule": "63351516df919f17849a6d85",\r\n  "toShiftofSchedule": "633518fe88caa1f4cc6d3107",\r\n  "doctor": "633ab54a9fd528b9532b8d59"\r\n}'
  });

  postman[Request]({
    name: "getDoctorShifts",
    id: "11bf5a71-c98e-4cac-9830-bd860065a768",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/getDoctorShifts",
    data:
      '{\r\n  "id": "633ab54a9fd528b9532b8d59",\r\n  "fromDate": "2022-10-12T06:59:48.000Z",\r\n  "toDate": "2022-10-15T06:59:48.000Z"\r\n}'
  });

  postman[Request]({
    name: "getShifts",
    id: "0e7fb71d-e950-49ba-a0c8-2caf68deb899",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/getShifts",
    data: '{\r\n    "id":"633ab0f123be88c950fb8a89"\r\n}'
  });

  postman[Request]({
    name: "getRequests",
    id: "dd3a905a-7287-4e27-9212-a6cf6d5b483c",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/getRequests",
    data: '{\r\n    "id":"633ab0f123be88c950fb8a89"\r\n}'
  });

  postman[Request]({
    name: "setRequestResponse",
    id: "7fbfa9cc-9702-43d5-aa3f-53e39da72bf1",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/setRequestResponse",
    data:
      '{\r\n    "requestId": "63659d816e7741c49acb48fd",\r\n    "Agree": true\r\n}'
  });
}
