// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    BaseUrl: "http://localhost:4000/"
  }
});

export default function() {
  postman[Request]({
    name: "changeClendar show doctor calendar",
    id: "38658122-cf30-4878-90e3-f9a6c295cb3b",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/changeClendar",
    data:
      '{\n    "id": "633ab0f123be88c950fb8a89",\n    "allawAllDoctors":false\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });

  postman[Request]({
    name: "changeClendar show all shecules",
    id: "6d2e3232-0420-46c2-9042-e4c16601e55e",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/changeClendar",
    data:
      '{\n    "id": "633ab0f123be88c950fb8a89",\n    "allawAllDoctors":false\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });

  postman[Request]({
    name: "changePassword",
    id: "80a6422d-3bb4-48cc-b7be-cab64cb61c34",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/changePassword",
    data:
      '{\n    "id" : "633ab0f123be88c950fb8a89",\n    "email": "abcd@gmail.com",\n    "password":"Abcd@1234"\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });

  postman[Request]({
    name: "defineRequirements",
    id: "31b4c969-6ac4-4df8-b606-08759bab1f72",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/defineRequirements",
    data:
      '{\n    "id":"633ab0f123be88c950fb8a89",\n    "date":"2022-10-14",\n    "morning": true,\n    "evening": false,\n    "night":true\n\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });

  postman[Request]({
    name: "setSwappingShifts",
    id: "c0dda641-36f6-4215-b4b9-ffb8dbc045a6",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/setSwappingShifts",
    data:
      '{\n  "id": "633ab0f123be88c950fb8a89",\n  "fromShiftofSchedule": "63351516df919f17849a6d85",\n  "toShiftofSchedule": "633518fe88caa1f4cc6d3107",\n  "doctor": "633ab54a9fd528b9532b8d59"\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });

  postman[Request]({
    name: "getDoctorShifts",
    id: "9a46af85-d365-4e6d-8af4-a84ae79b6e3f",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/getDoctorShifts",
    data:
      '{\n  "id": "633ab54a9fd528b9532b8d59",\n  "fromDate": "2022-11-12T06:59:48.000Z",\n  "toDate": "2022-11-15T06:59:48.000Z"\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });

  postman[Request]({
    name: "getShifts",
    id: "de1c3e47-5f90-496e-a92f-73a8001a61ba",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/getShifts",
    data: '{\n    "id":"633ab0f123be88c950fb8a89"\n}',
    headers: {
      "Content-Type": "application/json",
      "x-nick-name": "{{access_token}}"
    },
  });

  postman[Request]({
    name: "getRequests",
    id: "f898f088-f91e-4ad1-ad14-3ab4e4f4b841",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/getRequests",
    data: '{\n    "id":"633ab0f123be88c950fb8a89"\n}',
    headers: {
      "Content-Type": "application/json",
      "x-nick-name": "{{access_token}}"
    },
  });

  postman[Request]({
    name: "setRequestResponse",
    id: "fa027ba8-f751-4856-8425-8f61ea97e1ef",
    method: "POST",
    address: "{{BaseUrl}}api/doctor/setRequestResponse",
    data:
      '{\n    "requestId": "63659d816e7741c49acb48fd",\n    "Agree": true\n}',
    headers: {
        "Content-Type": "application/json",
        "x-nick-name": "{{access_token}}"
      },
    });
}
