// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
    options,
    environment: {
        BaseUrl: "http://localhost:4000/",
    },
});

export default function () {
    postman[Request]({
        name: "changeClendar show doctor calendar",
        id: "509e2294-ced4-4ed7-89c7-c1b76673d2cf",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/changeClendar",
        data: '{\r\n    "id": "633ab0f123be88c950fb8a89",\r\n    "allawAllDoctors":false\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "changeClendar show all shecules",
        id: "40e4f6be-f3cb-47a3-8084-3e26dda8095c",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/changeClendar",
        data: '{\r\n    "id": "633ab0f123be88c950fb8a89",\r\n    "allawAllDoctors":true\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "changePassword",
        id: "2b83f50f-fa18-4a07-aff1-bb4acd63d026",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/changePassword",
        data: '{\r\n    "id" : "633ab0f123be88c950fb8a89",\r\n    "email": "abcd@gmail.com",\r\n    "password":"Abcd@1234"\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "defineRequirements",
        id: "2c07e572-5eff-4eed-a273-5440dc738a11",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/defineRequirements",
        data: "{\r\n  id: '633ab0f123be88c950fb8a89',\r\n  date: '2022-11-09',\r\n  shiftTypes: [\r\n    { id: '633342d5b7cee2b016919f5e', checked: true },\r\n    { id: '633489c62018c4ed921a0852', checked: true },\r\n    { id: '63348a42457add832f5834c9', checked: false }\r\n  ]\r\n}",
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "setSwappingShifts",
        id: "df8c1a06-9349-4e97-a461-f7316c684341",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/setSwappingShifts",
        data: '{\r\n  "id": "633ab0f123be88c950fb8a89",\r\n  "fromShiftofSchedule": "63351516df919f17849a6d85",\r\n  "toShiftofSchedule": "633518fe88caa1f4cc6d3107",\r\n  "doctor": "633ab54a9fd528b9532b8d59"\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "getDoctorShifts",
        id: "ae6e910c-60a2-4b6c-a925-b8c0329c23eb",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/getDoctorShifts",
        data: '{\r\n  "id": "633ab54a9fd528b9532b8d59",\r\n  "fromDate": "2022-11-12T06:59:48.000Z",\r\n  "toDate": "2022-11-15T06:59:48.000Z"\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "getShifts",
        id: "59a3be30-9b06-43d2-aeb7-c82702598e19",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/getShifts",
        data: '{\r\n    "id":"633ab0f123be88c950fb8a89"\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "getRequests",
        id: "33352e28-a9e0-4a40-b602-7b645f51b6b9",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/getRequests",
        data: '{\r\n    "id":"633ab0f123be88c950fb8a89"\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });

    postman[Request]({
        name: "setRequestResponse",
        id: "bf9a1351-0e58-48f7-a91e-d508eb501b09",
        method: "POST",
        address: "{{BaseUrl}}api/doctor/setRequestResponse",
        data: '{\r\n    "requestId": "63659d816e7741c49acb48fd",\r\n    "Agree": true\r\n}',
        headers: {
            "Content-Type": "application/json",
            "x-nick-name": "{{access_token}}",
        },
    });
}
