# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy_to_heroku

on:
  push:
    branches: [ Server_deploy ]
  
jobs:
  Server_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
    - uses: actions/checkout@v3
    - name: Heroku Docker Container Deploy
    - run : git remote add heroku https://heroku:${{secreats.HEROKU_API_KEY}}@git.heroku.com/cedar247.git
    - name : deploy
    - run : git push heroku HEAD:Server_deploy -f
